[2023-12-04T18:00:32.211+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_local_to_psql.wget manual__2023-12-04T18:00:30.872544+00:00 [queued]>
[2023-12-04T18:00:32.234+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_local_to_psql.wget manual__2023-12-04T18:00:30.872544+00:00 [queued]>
[2023-12-04T18:00:32.235+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-04T18:00:32.267+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): wget> on 2023-12-04 18:00:30.872544+00:00
[2023-12-04T18:00:32.282+0000] {standard_task_runner.py:57} INFO - Started process 939 to run task
[2023-12-04T18:00:32.289+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_local_to_psql', 'wget', 'manual__2023-12-04T18:00:30.872544+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_local_to_psql.py', '--cfg-path', '/tmp/tmp5f97l_2b']
[2023-12-04T18:00:32.295+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask wget
[2023-12-04T18:00:32.479+0000] {task_command.py:416} INFO - Running <TaskInstance: etl_local_to_psql.wget manual__2023-12-04T18:00:30.872544+00:00 [running]> on host 9ac898278c26
[2023-12-04T18:00:32.754+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_local_to_psql' AIRFLOW_CTX_TASK_ID='wget' AIRFLOW_CTX_EXECUTION_DATE='2023-12-04T18:00:30.872544+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-04T18:00:30.872544+00:00'
[2023-12-04T18:00:32.760+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T18:00:32.762+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'curl -sS {url} > {AIRFLOW_HOME}/output.parquet']
[2023-12-04T18:00:32.797+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T18:00:32.804+0000] {subprocess.py:93} INFO - /bin/bash: line 1: {AIRFLOW_HOME}/output.parquet: No such file or directory
[2023-12-04T18:00:32.814+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-04T18:00:32.839+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-04T18:00:32.849+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_local_to_psql, task_id=wget, execution_date=20231204T180030, start_date=20231204T180032, end_date=20231204T180032
[2023-12-04T18:00:32.880+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task wget (Bash command failed. The command returned a non-zero exit code 1.; 939)
[2023-12-04T18:00:32.918+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-04T18:00:32.965+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
